### ISSUE TITLE
Duration greater than 120 minutes

### ISSUE THREAD

**Issue by phurth** [sh00t2kill/linktap_local_http_component#34] opened 2024-02-27 20:52 UTC
Hi! Nice work on this integration.

Sorry for the long background below, but I'd like to switch to using your integration so everything is working over HTTP rather than MQTT, but your integration seems to have a maximum configurable duration of 120 minutes. Would it be possible to change this so a longer duration could be selected?

I am using a Linktap valve in a somewhat non-traditional use case. Currently, I trigger a REST call to start/stop the valve and use the MQTT entities to provide sensor data from the valve. The reason I use REST is due to my use case: I use the valve to control well water to my RV, so it's not a normal "watering" scenario. Because of this, I use REST since this allows me to start the valve with a max duration of 86399 seconds (just under 24 hours). I have a Node-Red flow set up to restart nightly so long as I have a helper switch in Home Assistant "on". The net effect is the water stays on until I turn it off. As you may know, the valve will auto shut-off when the watering duration ends and there's no way to disable this.

**Comment by sh00t2kill** [comment] 2024-02-27 21:03
It's possible to change it, the issue is around usability.

5 minute increments from 5 to ~1500 is very unweidly in the UI.

What about a service call that allows you to s set the duration manually, in seconds, bypassing the number entity?

**Comment by phurth** [comment] 2024-02-27 21:28
A service call would be great. It's what I'm doing now with a direct REST call. I had all kinds of trouble getting turning on - and staying on - to work properly with MQTT. HTTP seemed much more reliable when I was testing.

Thanks!

**Comment by sh00t2kill** [comment] 2024-02-27 21:52
Too easy. I'll add something over the next few days.

Side thought, have you tried setting the number duration entity to 0?

I cant recall what this does in my integration but I have a feeling that 0 may make it water for the defined max of 1439.

**Comment by phurth** [comment] 2024-02-27 22:10
I believe I tried 0 but it didn't do what I needed (or didn't work at all, I can't recall). Working with their support, I landed on just restarting every 24 hours. It would be much easier if they just offered "always on" as an option, but they said that most of their dev effort was focused on new products and they didn't have much time devoted to enhancing the existing ones.

The resetting is a bit of an annoyance, but my use case also includes tracking volume over time so I can see when my softener needs to be regenerated and filters changed. The LinkTap valve stats and integration with Utility Meter in HA allow me to do this.

While I've been happy with the TapLink valve, I do have an eye on the new valve from Ecowitt (I have a bunch of their sensors and weather stations). There's no integration (yet) with HA, but it *does* have an always on setting.

**Comment by gkyprios** [comment] 2024-02-27 22:13
@phurth - try this out:

https://www.home-assistant.io/integrations/ecowitt

Works well! I have a weather station, pool temp sensor and many moisture sensors for my fruit trees.

**Comment by sh00t2kill** [comment] 2024-02-27 22:18
> I believe I tried 0 but it didn't do what I needed (or didn't work at all, I can't recall). Working with their support, I landed on just restarting every 24 hours. It would be much easier if they just offered "always on" as an option, but they said that most of their dev effort was focused on new products and they didn't have much time devoted to enhancing the existing ones.
> 
> The resetting is a bit of an annoyance, but my use case also includes tracking volume over time so I can see when my softener needs to be regenerated and filters changed. The LinkTap valve stats and integration with Utility Meter in HA allow me to do this.
> 
> While I've been happy with the TapLink valve, I do have an eye on the new valve from Ecowitt (I have a bunch of their sensors and weather stations). There's no integration (yet) with HA, but it _does_ have an always on setting.

I'm travelling at the moment so not easy to check. I couldn't remember if the 0 was passed through, or if 0 gets overridden to 15 minutes.

I will double check as maybe that's a better solution, and create an additional service as a fall back.

**Comment by sh00t2kill** [comment] 2024-02-27 22:59
I had a meeting cancelled.

new valve.start_watering service released in v0.4.8
I havent tested it thoroughly, but it "should just work"

**Comment by phurth** [comment] 2024-02-28 00:06
> @phurth - try this out:
> 
> https://www.home-assistant.io/integrations/ecowitt
> 
> Works well! I have a weather station, pool temp sensor and many moisture sensors for my fruit trees.

I'm using the Ecowitt integration for my sensors and weather stations and it does work great. The problem is with Ecowitt's new water control valve (the WFC01) which does not yet work with Home Assistant.

**Comment by gkyprios** [comment] 2024-02-28 00:07
Ah right. Thanks @phurth. Good to know as I have been looking at the valve as well.

**Comment by phurth** [comment] 2024-02-28 00:08
> I had a meeting cancelled.
> 
> new valve.start_watering service released in v0.4.8 I havent tested it thoroughly, but it "should just work"

Super fast - thanks! I'll give it a try as soon as I can. I'm up in the Northwoods where things will be winterized for a bit yet.

**Comment by sh00t2kill** [comment] 2024-02-28 02:32
0.4.8 had a bug so make sure you try out 0.4.9

**Comment by sh00t2kill** [comment] 2024-03-01 05:55
@phurth I will close this off, but please open it up again if there are any issues,

**Closed by sh00t2kill** 2024-03-01 05:55 UTC
